#!/bin/bash

VERSION="v1.2.1"

sed -i s/%version_placeholder%/$VERSION/g main.v internals/build.v

echo "building for linux..."
v main.v -o build/flunky

echo "building for windows..."
v main.v -o build/flunky.exe

sed -i s/$VERSION/%version_placeholder%/g main.v internals/build.v