#!/bin/bash

VERSION="v1.2.3"

sed -i s/%version_placeholder%/$VERSION/g main.v internals/build.v

if [ ! -d "build" ]; then
    mkdir "build"
fi

echo "building for linux..."
v . -os linux -o build/flunky

sed -i s/$VERSION/%version_placeholder%/g main.v internals/build.v